<?php

namespace justinholtweb\coinpurse\controllers;

use craft\web\Controller;
use justinholtweb\coinpurse\Plugin;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * The two things Apple Pay needs from the server that no other wallet does: a merchant session,
 * and a file at a fixed path proving the domain is ours.
 */
class ApplePayController extends Controller
{
    public array|bool|int $allowAnonymous = ['validate-merchant', 'domain-association'];

    /**
     * `beforeAction()` is a fixed public signature on the base controller; narrowing it to
     * `protected` is a compile-time fatal that disables the whole plugin.
     */
    public function beforeAction($action): bool
    {
        if ($action->id === 'domain-association') {
            // Apple fetches this file with no cookies and no token of ours. There is nothing to
            // forge: the response is a public, Apple-issued string tied to this domain.
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }

    /**
     * Exchange the browser's validation URL for a merchant session.
     */
    public function actionValidateMerchant(): Response
    {
        $this->requirePostRequest();
        $this->requireAcceptsJson();

        $validationUrl = (string)$this->request->getBodyParam('validationUrl');

        try {
            $session = Plugin::getInstance()->getApplePay()->createMerchantSession($validationUrl);
        } catch (\Throwable $e) {
            return $this->asJson(['success' => false, 'error' => $e->getMessage()]);
        }

        return $this->asJson(['success' => true, 'merchantSession' => $session]);
    }

    /**
     * Serve `/.well-known/apple-developer-merchantid-domain-association`.
     *
     * Apple fetches this with no session, no cookies and no CSRF token, from its own IP ranges, so
     * this action is anonymous and CSRF-exempt by necessity. It reveals nothing: the file's whole
     * purpose is to be public, and it is generated by Apple for this domain.
     */
    public function actionDomainAssociation(): Response
    {
        $this->requireSiteRequest();

        $contents = Plugin::getInstance()->getApplePay()->getDomainAssociation();

        if (!$contents) {
            throw new NotFoundHttpException('No Apple Pay domain association file is configured.');
        }

        $this->response->format = Response::FORMAT_RAW;
        $this->response->getHeaders()->set('Content-Type', 'text/plain; charset=UTF-8');

        // `yii\web\Response` has no `setContent()`; the content is a plain public property.
        $this->response->content = $contents;

        return $this->response;
    }
}
